spring:
  application:
    name: item-service
  cloud:
    config:
      override-none: true
  
    
server:
  port: 8001
server:
  port: 8002

  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
